[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"

[default.databases.postgres_db]
url = "postgres://postgres:postgres@localhost:5432/maadb"

[debug]
log_level = "debug"

[release]
log_level = "critical"
